server.port=3000

# Database Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Redis Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

# Security Keys
jwt.secret=${JWT_SECRET_KEY:supersecretkeywhichmustbeatleast256bitslongsothatitcanworkwithhmacsha256algorithm}

# API Keys
anthropic.api.key=${ANTHROPIC_API_KEY:dummy_key}
deepl.api.key=${DEEPL_API_KEY:dummy_key}
